# This file was generated by liblab | https://liblab.com/

from nyt_article_search import NytArticleSearch, Environment
from nyt_article_search.models import Facet, FacetFields, FacetFilter, Sort

sdk = NytArticleSearch(api_key="YOUR_API_KEY", base_url=Environment.DEFAULT.value)

result = sdk.search.get_articlesearch_json(
    begin_date="20220101",
    end_date="20220131",
    facet=Facet.FALSE,
    facet_fields=FacetFields.DAY_OF_WEEK,
    facet_filter=FacetFilter.FALSE,
    fl="fl",
    fq="fq",
    page=88,
    q="q",
    sort=Sort.NEWEST,
)

print(result)
